components:
  schemas:
    health-read-get-200-response:
      properties:
        message:
          type: string
      required:
        - message
      type: object
      example:
        message: ok
    health-read-get-500-response:
      properties:
        error:
          type: string
      required:
        - error
      type: object
  examples:
    health-read-get-200-response:
      value:
        message: ok
    health-read-get-500-response:
      value:
        error: Internal Server Error

info:
  description: ''
  title: Service1
  version: v1.0.2
openapi: 3.1.0

paths:
  /health:
    get:
      description: Service Health checks to poll for _'Aliveness'_.
      operationId: health-read
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/health-read-get-200-response'
              examples:
                health-read-200-response:
                  $ref: '#/components/examples/health-read-get-200-response'
          description: >-
            Successful response returned when the Service is alive and ready to
            process work.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/health-read-get-500-response'
              examples:
                health-read-500-response:
                  $ref: '#/components/examples/health-read-get-500-response'
          description: Catastrophic error of the Service. Report Issue.
      summary: ''
      tags:
        - Health
