name: Pimoroni Eink Screen Formatter action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'pimoroni_eink_screen_formatter/go.mod'
          check-latest: true
          cache-dependency-path: pimoroni_eink_screen_formatter/go.sum
      - name: Run program
        run: go run .
        working-directory: ./pimoroni_eink_screen_formatter
      - name: Run Tests
        run: go test
        working-directory: ./pimoroni_eink_screen_formatter
      - name: Vet program
        run: go vet
        working-directory: ./pimoroni_eink_screen_formatter
