# Links to using specmatic for contract testing:
#
# - https://specmatic.in/documentation/continuous_integration.html
# - https://github.com/marketplace/actions/setup-specmatic-environment
# - https://github.com/znsio/specmatic-order-api/blob/github-actions-setup-specmatic/.github/workflows/command_line_contract_tests.yml
name: Use OpenAPI Generated Server
on:
  push:
    paths:
      - 'use_openapi_generated_server/**'
      - '.github/workflows'

permissions:
  # https://github.com/mikepenz/action-junit-report#pr-run-permissions
  checks: write

jobs:
  local_build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'use_openapi_generated_server/go.mod'
          check-latest: true
          cache-dependency-path: use_openapi_generated_server/go.sum
      - name: Run Tests
        run: go test
        working-directory: ./use_openapi_generated_server
      - name: Vet program
        run: go vet
        working-directory: ./use_openapi_generated_server
      - name: Run program (and keep running)
        run: go run . &
        working-directory: ./use_openapi_generated_server
      - name: Setup specmatic
        uses: airslate-oss/setup-specmatic@v1
        with:
          specmatic-version: 2.17.3
      - name: Run Specmatic Gherkin tests
        working-directory: ./use_openapi_generated_server
        run: specmatic test --port 8087 --junitReportDir contract-test-reports petstore-expanded.spec
      - name: Kill server
        run: pkill use_openapi_generated_server
      - name: Publish contract test report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: '**/contract-test-reports/TEST-*.xml'

      - name: Run program (and keep running)
        run: go run . &
        working-directory: ./use_openapi_generated_server
      - name: Run Specmatic contract as test
        working-directory: ./use_openapi_generated_server
        run: specmatic test --port 8087 --junitReportDir contract-test-reports petstore-expanded-v3.yaml
      - name: Kill server
        run: pkill use_openapi_generated_server
      - name: Publish contract test report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: '**/contract-test-reports/TEST-*.xml'

  docker_build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: make build-docker
        working-directory: ./use_openapi_generated_server
      - name: Docker run unittests
        run: make unittest-docker
        working-directory: ./use_openapi_generated_server
      - name: Docker run contract tests
        run: make contracttest-docker
        working-directory: ./use_openapi_generated_server
      - name: Publish contract test report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: 'build/reports/specmatic/junit/TEST-*.xml'

